USE [CASA_NATURA]
GO

/****** Object:  StoredProcedure [dbo].[REGISTRO_SP]    Script Date: 7/5/2025 10:00:17 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[REGISTRO_SP] 
    @NOMBRE VARCHAR(100), 
    @APELLIDO1 VARCHAR(100), 
    @APELLIDO2 VARCHAR(100), 
    @CORREO VARCHAR(100), 
    @CONTRASENNA VARCHAR(100), 
    @IDENTIFICACION VARCHAR(20)
AS
BEGIN
    SET NOCOUNT ON;

    IF EXISTS (SELECT 1 FROM USUARIOS_TB WHERE CORREO = @CORREO)
    BEGIN
        RAISERROR('El correo ya está registrado.', 16, 1);
        RETURN;
    END

    -- Insertar el usuario con contraseña encriptada (hash)
    INSERT INTO USUARIOS_TB (NOMBRE, APELLIDO1, APELLIDO2, CORREO, PASSWORD, IDENTIFICACION, ID_ESTADO, ID_ROL)
    VALUES (
        @NOMBRE, 
        @APELLIDO1, 
        @APELLIDO2, 
        @CORREO, 
        CONVERT(VARCHAR(64), HASHBYTES('SHA2_256', @CONTRASENNA), 2), --AQUI ESTAMOS HASHEANDO LA CONTRASENNA
        @IDENTIFICACION, 1,1
    );
END;
GO

ALTER PROCEDURE [dbo].[REGISTRO_SP] 
    @NOMBRE VARCHAR(100), 
    @APELLIDO1 VARCHAR(100), 
    @APELLIDO2 VARCHAR(100), 
    @CORREO VARCHAR(100), 
    @CONTRASENNA VARCHAR(100), 
    @IDENTIFICACION VARCHAR(20),
    @RESULTADO INT OUTPUT
AS
BEGIN
    SET NOCOUNT ON;

    IF EXISTS (SELECT 1 FROM USUARIOS_TB WHERE CORREO = @CORREO)
    BEGIN
        SET @RESULTADO = -1; -- Correo ya registrado
        RETURN;
    END

    INSERT INTO USUARIOS_TB (NOMBRE, APELLIDO1, APELLIDO2, CORREO, PASSWORD, IDENTIFICACION, ID_ESTADO, ID_ROL)
    VALUES (
        @NOMBRE, 
        @APELLIDO1, 
        @APELLIDO2, 
        @CORREO, 
        CONVERT(VARCHAR(64), HASHBYTES('SHA2_256', @CONTRASENNA), 2),
        @IDENTIFICACION,
        1, -- ID_ESTADO (activo, por ejemplo)
        1  -- ID_ROL (usuario normal, por ejemplo)
    );

    SET @RESULTADO = 1; -- Registro exitoso
END;
GO
