//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTIVIDADES_TB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ACTIVIDADES_TB()
        {
            this.USUARIO_ACTIVIDAD_TB = new HashSet<USUARIO_ACTIVIDAD_TB>();
            this.USUARIO_ACTIVIDAD_TB1 = new HashSet<USUARIO_ACTIVIDAD_TB>();
        }
    
        public int ID_ACTIVIDAD { get; set; }
        public string DESCRIPCION { get; set; }
        public System.DateTime FECHA { get; set; }
        public decimal PRECIO_BOLETO { get; set; }
        public Nullable<int> TICKETS_DISPONIBLES { get; set; }
        public Nullable<int> TICKETS_VENDIDOS { get; set; }
        public int ID_ESTADO { get; set; }
        public string IMAGEN { get; set; }
        public string TIPO { get; set; }
        public string NOMBRE { get; set; }
    
        public virtual ESTADOS_TB ESTADOS_TB { get; set; }
        public virtual ESTADOS_TB ESTADOS_TB1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIO_ACTIVIDAD_TB> USUARIO_ACTIVIDAD_TB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIO_ACTIVIDAD_TB> USUARIO_ACTIVIDAD_TB1 { get; set; }
    }
}
