//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class APADRINAMIENTOS_TB
    {
        public int ID_APADRINAMIENTO { get; set; }
        public decimal MONTO_MENSUAL { get; set; }
        public System.DateTime FECHA { get; set; }
        public System.DateTime FECHA_BAJA { get; set; }
        public int ID_USUARIO { get; set; }
        public int ID_ESTADO { get; set; }
        public int ID_ANIMAL { get; set; }
    
        public virtual ANIMAL_TB ANIMAL_TB { get; set; }
        public virtual ESTADOS_TB ESTADOS_TB { get; set; }
        public virtual USUARIOS_TB USUARIOS_TB { get; set; }
    }
}
