//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class APADRINAMIENTOS_TB
    {
        public int ID_APADRINAMIENTO { get; set; }
        public decimal MONTO_MENSUAL { get; set; }
        public System.DateTime FECHA { get; set; }
        public Nullable<System.DateTime> FECHA_BAJA { get; set; }
        public int ID_USUARIO { get; set; }
        public int ID_ESTADO { get; set; }
        public int ID_ANIMAL { get; set; }
        public int ID_METODO { get; set; }
        public string REFERENCIA { get; set; }
    
        public virtual ANIMAL_TB ANIMAL_TB { get; set; }
        public virtual ANIMAL_TB ANIMAL_TB1 { get; set; }
        public virtual ANIMAL_TB ANIMAL_TB2 { get; set; }
        public virtual ESTADOS_TB ESTADOS_TB { get; set; }
        public virtual ESTADOS_TB ESTADOS_TB1 { get; set; }
        public virtual ESTADOS_TB ESTADOS_TB2 { get; set; }
        public virtual METODO_PAGO_TB METODO_PAGO_TB { get; set; }
        public virtual METODO_PAGO_TB METODO_PAGO_TB1 { get; set; }
        public virtual METODO_PAGO_TB METODO_PAGO_TB2 { get; set; }
        public virtual USUARIOS_TB USUARIOS_TB { get; set; }
        public virtual USUARIOS_TB USUARIOS_TB1 { get; set; }
        public virtual USUARIOS_TB USUARIOS_TB2 { get; set; }
    }
}
