//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CANTONES_TB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CANTONES_TB()
        {
            this.DISTRITOS_TB = new HashSet<DISTRITOS_TB>();
            this.DISTRITOS_TB1 = new HashSet<DISTRITOS_TB>();
            this.DISTRITOS_TB2 = new HashSet<DISTRITOS_TB>();
        }
    
        public int ID_CANTON { get; set; }
        public string NOMBRE { get; set; }
        public int PROVINCIA { get; set; }
    
        public virtual PROVINCIAS_TB PROVINCIAS_TB { get; set; }
        public virtual PROVINCIAS_TB PROVINCIAS_TB1 { get; set; }
        public virtual PROVINCIAS_TB PROVINCIAS_TB2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DISTRITOS_TB> DISTRITOS_TB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DISTRITOS_TB> DISTRITOS_TB1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DISTRITOS_TB> DISTRITOS_TB2 { get; set; }
    }
}
