//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CANTONES_TB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CANTONES_TB()
        {
            this.DISTRITOS_TB = new HashSet<DISTRITOS_TB>();
        }
    
        public int ID_CANTON { get; set; }
        public string NOMBRE { get; set; }
        public int PROVINCIA { get; set; }
    
        public virtual PROVINCIAS_TB PROVINCIAS_TB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DISTRITOS_TB> DISTRITOS_TB { get; set; }
    }
}
