//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONSULTAS_TB
    {
        public int ID_CONSULTA { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO { get; set; }
        public string CORREO { get; set; }
        public string MENSAJE { get; set; }
        public System.DateTime FECHA { get; set; }
        public string ESTADO { get; set; }
        public Nullable<System.DateTime> FECHA_RESUELTA { get; set; }
    }
}
