//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIRECCIONES_TB
    {
        public int ID_DIRECCION { get; set; }
        public int ID_DISTRITO { get; set; }
        public string DIRECCION_EXACTA { get; set; }
        public int ID_USUARIO { get; set; }
        public int ID_ESTADO { get; set; }
    
        public virtual DISTRITOS_TB DISTRITOS_TB { get; set; }
        public virtual ESTADOS_TB ESTADOS_TB { get; set; }
        public virtual USUARIOS_TB USUARIOS_TB { get; set; }
    }
}
