//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIRECCIONES_TB
    {
        public int ID_DIRECCION { get; set; }
        public int ID_DISTRITO { get; set; }
        public string DIRECCION_EXACTA { get; set; }
        public int ID_USUARIO { get; set; }
        public int ID_ESTADO { get; set; }
    
        public virtual DISTRITOS_TB DISTRITOS_TB { get; set; }
        public virtual DISTRITOS_TB DISTRITOS_TB1 { get; set; }
        public virtual DISTRITOS_TB DISTRITOS_TB2 { get; set; }
        public virtual ESTADOS_TB ESTADOS_TB { get; set; }
        public virtual ESTADOS_TB ESTADOS_TB1 { get; set; }
        public virtual ESTADOS_TB ESTADOS_TB2 { get; set; }
        public virtual USUARIOS_TB USUARIOS_TB { get; set; }
        public virtual USUARIOS_TB USUARIOS_TB1 { get; set; }
        public virtual USUARIOS_TB USUARIOS_TB2 { get; set; }
    }
}
