//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISTRITOS_TB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DISTRITOS_TB()
        {
            this.DIRECCIONES_TB = new HashSet<DIRECCIONES_TB>();
        }
    
        public int ID_DISTRITO { get; set; }
        public string NOMBRE { get; set; }
        public int CANTON { get; set; }
    
        public virtual CANTONES_TB CANTONES_TB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIRECCIONES_TB> DIRECCIONES_TB { get; set; }
    }
}
