//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISTRITOS_TB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DISTRITOS_TB()
        {
            this.DIRECCIONES_TB = new HashSet<DIRECCIONES_TB>();
            this.DIRECCIONES_TB1 = new HashSet<DIRECCIONES_TB>();
            this.DIRECCIONES_TB2 = new HashSet<DIRECCIONES_TB>();
        }
    
        public int ID_DISTRITO { get; set; }
        public string NOMBRE { get; set; }
        public int CANTON { get; set; }
    
        public virtual CANTONES_TB CANTONES_TB { get; set; }
        public virtual CANTONES_TB CANTONES_TB1 { get; set; }
        public virtual CANTONES_TB CANTONES_TB2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIRECCIONES_TB> DIRECCIONES_TB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIRECCIONES_TB> DIRECCIONES_TB1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIRECCIONES_TB> DIRECCIONES_TB2 { get; set; }
    }
}
