//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONACIONES_TB
    {
        public int ID_DONACION { get; set; }
        public Nullable<decimal> MONTO { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public int ID_USUARIO { get; set; }
        public int ID_METODO { get; set; }
    
        public virtual METODO_PAGO_TB METODO_PAGO_TB { get; set; }
        public virtual USUARIOS_TB USUARIOS_TB { get; set; }
    }
}
