//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONACIONES_TB
    {
        public int ID_DONACION { get; set; }
        public Nullable<decimal> MONTO { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public int ID_USUARIO { get; set; }
        public int ID_METODO { get; set; }
    
        public virtual METODO_PAGO_TB METODO_PAGO_TB { get; set; }
        public virtual USUARIOS_TB USUARIOS_TB { get; set; }
    }
}
