//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESPECIES_TB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ESPECIES_TB()
        {
            this.RAZAS_TB = new HashSet<RAZAS_TB>();
        }
    
        public int ID_ESPECIE { get; set; }
        public string NOMBRE { get; set; }
        public int ID_ESTADO { get; set; }
    
        public virtual ESTADOS_TB ESTADOS_TB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RAZAS_TB> RAZAS_TB { get; set; }
    }
}
