//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGISTRO_ERRORES_TB
    {
        public int ID_ERROR { get; set; }
        public Nullable<int> ID_USUARIO { get; set; }
        public System.DateTime FECHA_ACTUAL { get; set; }
        public string MENSAJE { get; set; }
    
        public virtual USUARIOS_TB USUARIOS_TB { get; set; }
    }
}
