//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGISTRO_ERRORES_TB
    {
        public int ID_ERROR { get; set; }
        public Nullable<int> ID_USUARIO { get; set; }
        public System.DateTime FECHA_ACTUAL { get; set; }
        public string MENSAJE { get; set; }
    }
}
