//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROLES_TB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ROLES_TB()
        {
            this.USUARIOS_TB = new HashSet<USUARIOS_TB>();
            this.USUARIOS_TB1 = new HashSet<USUARIOS_TB>();
            this.USUARIOS_TB2 = new HashSet<USUARIOS_TB>();
        }
    
        public int ID_ROL { get; set; }
        public string ROL { get; set; }
        public int ID_ESTADO { get; set; }
    
        public virtual ESTADOS_TB ESTADOS_TB { get; set; }
        public virtual ESTADOS_TB ESTADOS_TB1 { get; set; }
        public virtual ESTADOS_TB ESTADOS_TB2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIOS_TB> USUARIOS_TB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIOS_TB> USUARIOS_TB1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIOS_TB> USUARIOS_TB2 { get; set; }
    }
}
