//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROLES_TB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ROLES_TB()
        {
            this.USUARIOS_TB = new HashSet<USUARIOS_TB>();
        }
    
        public int ID_ROL { get; set; }
        public string ROL { get; set; }
        public int ID_ESTADO { get; set; }
    
        public virtual ESTADOS_TB ESTADOS_TB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIOS_TB> USUARIOS_TB { get; set; }
    }
}
